# This option allows you to set where
# player's data do you want to save.
Player-Data:
  Storage: mysql
  MySQL:
    hostname: adriftus.com
    username: adriftus_minecraft_main
    database: adriftus_GadgetsMenu
    port: 3306
    password: adriftus2020
    useSSL: true
Cosmetic-Item-Purchase:
  Enabled: true
  # Set the storage where do you want to save mystery dust.
  # Available storages: 'default', 'coinsapi', 'playerpoints', 'vault'.
  # 'default' represent follow player data storage.
  Mystery-Dust-Storage: default
  Enabled-Cosmetics:
    Hats: true
    Animated Hats: true
    Particles: true
    Suits: false
    Gadgets: true
    Pets: true
    Morphs: true
    Banners: true
    Emotes: true
    Cloaks: false
    Miniatures: true
  Reopen-GUI-Menu-After-Purchase: true
  Execute-Command:
    # Set to true will use 3rd plugin to store purchased cosmetic items,
    # otherwise will saved in built-in storage.
    Enabled: false
    Command: pex user {PLAYER} add {PERMISSION}
Settings:
  Starting-Mystery-Dust: 0
  Max-Pet-Name-Characters: 20
  Gadget-Slot: 5
  Default-Self-Morph-View: true
  Enabled-Self-Morph-View: true
  Enabled-Mob-Disguise-Damage: true
  Auto-Equip-After-Purchase: true
  Auto-Equip-On-Loot-Found: true
  Show-Particle-Effect-To-Everyone: true
  Show-Cloak-Effect-To-Everyone: true
  Hide-Particle-Effect-For-Vanished-Player: true
  Hide-Cloak-Effect-For-Vanished-Player: true
  Equip-Cosmetic-Item-To-Slot: WARN
  Sync-Cosmetics-On-Join: true
  Inventory-Sorting: DEFAULT
  Show-Name-For-Mob-Disguise: true
  # The default value of Mystery Vault animation.
  # The animation the player who join the server first time.
  # Animation: None, Normal, CountDown, Star, Crafting, Summer, Halloween, Holiday
  Default-Mystery-Vault-Animation: NORMAL
Menu-Item:
  Name: '&aGadgetsMenu'
  Material: NETHER_STAR
  Slot: 4
  Give-On-Join: false
  Able-To-Move: false
  Lore:
  - '&7Mystery Dust: &b{MYSTERY_DUST}'
  - ''
  - '&7Enjoy fun cosmetic features!'
  - '&7More stuff will be added over time,'
  - '&7make sure to check our update forums!'
  - '&7Thanks you for supporting our server.'
  Click-Type: LEFT_AND_RIGHT
Enabled-Worlds:
- world
- world_nether
- world_the_end
- castellum
- spawn
- spawns
- spooky
- halloween
- bskyblock_world
Disabled-Cosmetics:
  Hats: false
  Animated Hats: false
  Particles: false
  Suits: true
  Gadgets: false
  Pets: false
  Morphs: false
  Banners: false
  Emotes: false
  Cloaks: false
  Miniatures: false
Permission:
  No-Permission:
    Show-In-Lore: false
    Close-GUI-Menu-After-Select: true
    Lore:
    - ''
    - '&7Status: &c&lLOCKED'
    Play-Sound:
      Enabled: true
      Sound: ENTITY_ENDERMAN_TELEPORT
    Show-Custom-Item:
      Enabled: true
      Material: GRAY_DYE
  Has-Permission:
    Show-In-Lore: false
    Close-GUI-Menu-After-Select: true
    Lore:
    - ''
    - '&7Status: &a&lUNLOCKED'
    Play-Sound:
      Enabled: true
      Sound: ENTITY_EXPERIENCE_ORB_PICKUP
Item-Cost-Discount:
  Enabled: true
  Discount:
    Cosmetic-Item: true
    Crafting-Mystery-Box: true
  Discount-Rates:
    VIP:
      Priority: 1
      Permission: gadgetsmenu.discount.VIP
      Rate: 20
      Lore:
        Enough-Mystery-Dust:
        - ''
        - '&8&mRegular: {COST} Mystery Dust!'
        - '&aVIP&7: &a{VIP_COST} &7Mystery Dust (&a20% &7OFF!) &e◀'
        - '&cMVP: {MVP_COST} Mystery Dust (40% OFF!)'
        - ''
        - '&7Your Cost: &a{VIP_COST} &7Mystery Dust'
        - '&eClick to craft!'
        Not-Enough-Mystery-Dust:
        - ''
        - '&8&mRegular: {COST} Mystery Dust!'
        - '&aVIP&7: &a{VIP_COST} &7Mystery Dust (&a20% &7OFF!) &e◀'
        - '&cMVP: {MVP_COST} Mystery Dust (40% OFF!)'
        - ''
        - '&7Your Cost: &c{VIP_COST} &7Mystery Dust'
        - '&cYou need &b{COST_LEFT} &cmore mystery dust!'
    MVP:
      Priority: 2
      Permission: gadgetsmenu.discount.MVP
      Rate: 40
      Lore:
        Enough-Mystery-Dust:
        - ''
        - '&8&mRegular: {COST} Mystery Dust!'
        - '&8&mVIP: {VIP_COST} Mystery Dust (20% OFF!)'
        - '&bMVP&7: &a{MVP_COST} &7Mystery Dust (&a40% &7OFF!) &e◀'
        - ''
        - '&7Your Cost: &a{MVP_COST} &7Mystery Dust'
        - '&eClick to craft!'
        Not-Enough-Mystery-Dust:
        - ''
        - '&8&mRegular: {COST} Mystery Dust!'
        - '&8&mVIP: {VIP_COST} Mystery Dust (20% OFF!)'
        - '&bMVP&7: &a{MVP_COST} &7Mystery Dust (&a40% &7OFF!) &e◀'
        - ''
        - '&7Your Cost: &a{MVP_COST} &7Mystery Dust'
        - '&cYou need &b{COST_LEFT} &cmore mystery dust!'
Back-To-Main-Menu:
  Execute-Commands:
    Enabled: false
    Commands:
    - cc open menu.yml {PLAYER}
Fill-Empty-Slot-With-Item:
  Enabled: false
  Material: BLACK_STAINED_GLASS_PANE
Disabled-Commands:
- hat
Check-Update: true
Auto-Update: true
# Do not edit this.
Config-Version: 2.0.3
Cosmetics-Sync-On-Join:
  Hats: true
  Animated Hats: true
  Particles: true
  Suits: true
  Gadgets: true
  Pets: true
  Miniatures: true
  Morphs: true
  Banners: true
  Emotes: true
  Cloaks: true
Anti-Lag:
  Enabled: true
  Minimum-TPS: 17
  Action:
    Clear-Cosmetics: true
    Disable-Usage: true
Blacklisted-Regions:
  Disable-All-Cosmetics:
  - region1
  - region2
  - region3
  Disable-Hats: ''
  Disable-Animated-Hats: ''
  Disable-Particles: ''
  Disable-Suits: ''
  Disable-Gadgets: ''
  Disable-Pets: ''
  Disable-Miniatures: ''
  Disable-Morphs: ''
  Disable-Banners: ''
  Disable-Emotes: ''
  Disable-Cloaks: ''
  Disable-Pet-Riding: ''
